export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',

  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',

  SESSION_REVOKED: 'SESSION_REVOKED',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  RATE_LIMITED: 'RATE_LIMITED',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INVALID_REQUEST: 'INVALID_REQUEST',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
